#!/bin/bash

# get this by udevadm info /dev/input/eventX
device='/dev/input/by-id/usb-STMicroelectronics_STM32_IRMP_HID-KBD-Device_390D55745641-event-kbd'
#device='/dev/input/event4'
event_refresh='*code 173 (KEY_REFRESH), value 1'
event_blank='*code 48 (KEY_B), value 1*'
event_esc='*code 1 (KEY_ESC), value 1*'
event_f5='*code 63 (KEY_F5), value 1*'
event_prev='*code 104 (KEY_PAGEUP), value 1*'
event_next='*code 109 (KEY_PAGEDOWN), value 1*'


/usr/bin/evtest "$device" | while read line; do
  case $line in
    ($event_refresh)	date >> /var/log/started_by_IRMP_STM32_KBD ;;
    ($event_blank) 	echo "BLANK SCREEN" ;;
    ($event_f5)    	echo "F5" ;;
    ($event_esc)   	echo "ESCAPE" ;;
    ($event_prev)  	echo "PREVIOUS" ;;
    ($event_next)  	echo "NEXT" ;;
  esac
done
