#!/bin/bash

SVDRPCMD=/path/svdrpsend

skipmsg=skip
if [ "$(stat -c %Y /var/log/started_by_IRMP_STM32_KBD)" -lt "$(stat -c %Y /var/log/boot.msg)" ];
then {
echo skip >> /var/log/started_by_IRMP_STM32_KBD
date >> /var/log/started_by_IRMP_STM32_KBD
$SVDRPCMD MESG $skipmsg &
exit 0
}
fi;

msg=shutdown
$SVDRPCMD MESG $msg &

/path/stm32kbdIRalarm -s $(($2 - 300))

shutdown -h now
