#!/bin/bash

SVDRPCMD=/path/svdrpsend

skipmsg=skip
if [ /var/log/started_by_IRMP_STM32_KBD -ot /var/log/boot.msg ];
then {
echo skip >> /var/log/started_by_IRMP_STM32_KBD
date >> /var/log/started_by_IRMP_STM32_KBD
$SVDRPCMD MESG $skipmsg &
exit 1
}
fi;

msg=shutdown
$SVDRPCMD MESG $msg &

/path/stm32kbdIRalarm -s $(($2 - 300))

shutdown -h now
